<?php
declare(strict_types=1);

namespace labo86\staty;


class ErrMsg
{

    const DIRECTORY_DOES_NOT_EXIST = "DIRECTORY_DOES_NOT_EXIST";
    const DIRECTORY_PATH_IS_A_FILE = "DIRECTORY_PATH_IS_A_FILE";
    const ERROR_UNLINKING_EXISTENT_FILE = "ERROR_UNLINKING_EXISTENT_FILE";
    const ERROR_REMOVING_DIRECTORY = "ERROR_REMOVING_DIRECTORY";
    const ERROR_UNLINKING_SYMLINK = "ERROR_UNLINKING_SYMLINK";
    const ERROR_MAKING_SYMLINK = "ERROR_MAKING_SYMLINK";
    const CANNOT_COMPARE_ABSOLUTE_AND_RELATIVE_PATH = "ABSOLUTE_AND_RELATIVE_PATH_ARE_INCOMPATIBLE";
    const SOURCE_FILE_DOES_NOT_EXIST = "SOURCE_FILE_DOES_NOT_EXIST";
    const FILENAME_DOES_NOT_EXIST = "FILENAME_DOES_NOT_EXIST";
    const TARGET_DIRECTORY_IS_NOT_A_DIRECTORY = "TARGET_DIRECTORY_IS_NOT_A_DIRECTORY";
}